### ISSUE TITLE
Use connected nodeboxes to make signs-on-fenceposts connect to other nearby fences?

### ISSUE THREAD

**Issue by VanessaE** [minetest-mods/signs_lib#10]
Title says it all.

**Comment by sofar** [comment]
use minetest.override to override the fences to connect to your signs  (connects_to)

then, use connect_sides on the sign to tell it to only connect from the back?

**Comment by VanessaE** [comment]
That's what I was thinking of doing (well, from the sides too, if possible).  This was more of a reminder and "let's see if we can do this when someone (me?) gets time to fiddle with it" issue.

**Comment by VanessaE** [comment]
Connected nodeboxes don't respect facedir.
