### ISSUE TITLE
Text partially and (later) fully invisible on signs in some areas

### ISSUE THREAD

**Issue by redblade7** [minetest-mods/signs_lib#2]
When signs are placed in certain areas (not sure what the differences are), the following happens:
1. The text correctly shows on the sign
2. Teleport/travelnet/turn around, walk away, walk back to the sign
3. The text on the sign will be partially visible, the visible portion changing as you move the mouse
4. Repeat step #2
5. The text on the sign is completely invisible.
6. Have fun playing Minetest
7. Quit the game
8. Come back later
9. Return to step #1

All signs placed directly on the ground are always completely blank.

This started sometime in January 2016, likely when the signs were still part of homedecor_modpack. After discussion on the signs_lib forum thread, VanessaE said to file the bug here.

Step #3 example:
![turnaroundandgoback-edit](https://cloud.githubusercontent.com/assets/15269155/12708388/ccfc2f70-c896-11e5-9ce9-a4cb2f089dc3.png)

Step #5 example:
![turnaroundandgobackagain-edit](https://cloud.githubusercontent.com/assets/15269155/12708387/cce33b14-c896-11e5-92a4-e64f56ad56dc.png)

**Comment by redblade7** [comment]
I took a look at the affected signs, and noticed that in every case, the player is facing west (per F5).

**Comment by VanessaE** [comment]
It should be noted that signs laying flat on the ground aren't supposed to show their text.  Such a fix is possible, but not high-priority right now.

**Comment by kaeza** [comment]
Can you please test the [`fix1` tree](https://github.com/VanessaE/signs_lib/tree/fix1) ([ZIP here](https://github.com/VanessaE/archive/fix1.zip))?

**Comment by redblade7** [comment]
I mentioned to kaeza on IRC that The Terrarium was rebooted as The Creative Gardens, where I did not include the mods experimental mapgen, pipeworks, or technic, which were causing trouble and crashes on the Terrarium.

On the new server (The Creative Gardens) I have had no problems with the master branch, other than the signs laying flat on the ground issue.

I created a local server using the mods mentioned above and the signs_lib fix1 tree. No problems there other than the signs laying flat on the ground bug, although attempts to burn a mg-generated city with corium, lava, and fire crashed my client, so I'm wondering if the impossible-to-remove experimental mapgen mod was the cause, not signs_lib.

**Comment by tenplus1** [comment]
Tried your fix Kaeza, some signs wouldnt display at all and just returned after sign_info being nil.

**Comment by sofar** [comment]
@kaeza any chance you can fix the signs laying flat on the ground issue?

**Comment by VanessaE** [comment]
The Z-fighting issue should be fixed now.  fef163662a802a2cf2f65716ef6ce0d378ecf860

**Comment by VanessaE** [comment]
The official repo for this project has been moved to Gitlab.  Please copy/paste/re-open your issue there.  https://gitlab.com/VanessaE/signs_lib/issues
