### ISSUE TITLE
Recipe conflict with cottages

### ISSUE THREAD

**Issue by mase76** [minetest-mods/signs_lib#22]
Hi!
There is an older issue in the cottages mod, which has not been fixed yet.
The steel sign recipe conflicts with the hammer.
https://github.com/Sokomine/cottages/issues/2

**Comment by VanessaE** [comment]
There is no recipe in this mod to create a plain metal sign -- it uses default metal sign where it's needed, and appears to have for quite some time.   That said, there WAS a conflict (with the same recipe) that was supposed to create a locked wooden sign.  I've removed that recipe.  Instead, put a default wooden sign above a steel ingot.

**Comment by mase76** [comment]
I don't know, if you got me right. I am still not able to build a default:sign_wall_steel.
The six steel ingots above a stick ends up in a hammer.

**Comment by VanessaE** [comment]
At this point, that will be a conflict between minetest_game and cottages.  @Sokomine fix your busted-ass mod :wink:
