### ISSUE TITLE
Game crash if an area (with singn) loaded

### ISSUE THREAD

**Issue by bell07** [minetest-mods/signs_lib#24]
Something seems to be wrong in my world, but please do not crash the game
`ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'signs_lib' in callback luaentity_Activate(): ...mods/decor-mymodpack/signs_lib/init.lua:318: attempt to index local 'n' (a nil value)
`

**Comment by VanessaE** [comment]
You're using an outdated signs_lib -- it was removed from homedecor 2 years ago.

Delete your copy of homedecor, and get a fresh copy from here:  https://github.com/minetest-mods/homedecor_modpack

Get a fresh copy of signs_lib from this repo you've reported this issue in.

**Comment by bell07** [comment]
I use the version from this minetest-mods repository, not the version from homedecor_modpack
```
$ git remote -v
origin	https://github.com/minetest-mods/signs_lib (fetch)
origin	https://github.com/minetest-mods/signs_lib (push)
```

**Comment by VanessaE** [comment]
OH, I misread it, sorry.

**Comment by VanessaE** [comment]
Looks like somehow signs_lib's update function is being called from an unknown node.  Did you remove a mod recently that defined its own signs?

**Comment by bell07** [comment]
It is an old world that was not active for some months and I desired to play again. I cannot remember deactivation of any mods but there was different updates for different mods. I use bash scripts to get all mods allways up-to-date trough git.

**Comment by VanessaE** [comment]
#32 is merged -- see if that fixes it for you.

**Comment by bell07** [comment]
Tested shortly, the issue does not appear anymore
