### ISSUE TITLE
no text is rendered if first line is blank

### ISSUE THREAD

**Issue by codexp** [minetest-mods/signs_lib#27]
if you leave the first line blank (to center text vertically), it does not render anything.

**Comment by VanessaE** [comment]
A known issue.  The workaround is to just put a space in the line (e.g. space-enter)

**Comment by codexp** [comment]
I think a natural/default behavior of a sign should be that it centers text not only horizontally but also vertically.
Then putting empty lines wouldn't be necessary.

**Comment by VanessaE** [comment]
I tend to agree with you, @codexp.  @kaeza  *poke*

**Comment by VanessaE** [comment]
The official repo for this project has been moved to Gitlab.  Please copy/paste/re-open your issue there.  https://gitlab.com/VanessaE/signs_lib/issues
