### ISSUE TITLE
No way to set text position if registering a sign from another mod?

### ISSUE THREAD

**Issue by cheapie** [minetest-mods/signs_lib#5]
I've been reading through init.lua, and while it looks like there is support for other mods to register signs, I don't see any way for them to set the text position.

**Comment by VanessaE** [comment]
Fixed (b85eabb58ddf79e466a0fd3fbe17e4c33941098e).  Add a "textpos" stanza to your node definition, in the same format as seen near the top of signs_lib/init.lua.  For example:

```lua
minetest.register_node("extra_signs:my_extra_sign", {
	description = "my extra sign",
	--
	-- other stuff here ...
	--
	textpos = {
		{delta = { x =  0,    y = 0.07, z = -0.08 }, yaw = 0},
		{delta = { x = -0.08, y = 0.07, z =  0    }, yaw = math.pi / -2},
		{delta = { x =  0,    y = 0.07, z =  0.08 }, yaw = math.pi},
		{delta = { x =  0.08, y = 0.07, z =  0    }, yaw = math.pi / 2},
	}
end
```
(that was copied from the yard sign def)
