### ISSUE TITLE
Entity overload

### ISSUE THREAD

**Issue by tenplus1** [minetest-mods/signs_lib#8]
Too many signs in one area can cause entity overload and errors appear with 99+ objects being deleted which includes player at times...  Empty signs create entities so would it be possible to only have them when text is present ?

**Comment by kaeza** [comment]
>objects being deleted which includes player at times

This is an issue in the engine and cannot be fixed here.

>Empty signs create entities so would it be possible to only have them when text is present ?

This can be arranged.

**Comment by VanessaE** [comment]
The engine-deletes-player bug has since been fixed, and the apparent "overload" is another engine bug.

**Comment by VanessaE** [comment]
The official repo for this project has been moved to Gitlab.  Please copy/paste/re-open your issue there.  https://gitlab.com/VanessaE/signs_lib/issues
